package ISMS.views;

import ISMS.models.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class SuppliersView extends javax.swing.JPanel {

    /**
     * Creates new form SuppliersView
     */
    public SuppliersView() {
        initComponents();
        loadProducts();
        loadSupplier("");
    }

    private void loadProducts() {
        String query = "SELECT product_id, name FROM product";
        try (Connection con = Dbconnect.getConnection(); Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            cmbProduct.removeAllItems();
            cmbProduct.addItem(new ComboItem(0, "Select a Product"));
            while (rs.next()) {
                int id = rs.getInt("product_id");
                String name = rs.getString("name");

                ComboItem item = new ComboItem(id, name);
                cmbProduct.addItem(item);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading Products: " + ex.getMessage());
        }
    }

    public void addSupplier(String name, String contact_info) {
        String query = "INSERT INTO Supplier (name, contact_info) VALUES (?, ?)";
        try (Connection conn = Dbconnect.getConnection(); PreparedStatement pst = conn.prepareStatement(query)) {
            pst.setString(1, name);
            pst.setString(2, contact_info);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier added successfully!");
            loadSupplier("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding Supplier: " + e.getMessage());
        }

    }

    public void loadSupplier(String keyword) {
        Connection conn = Dbconnect.getConnection();
        DefaultTableModel model = (DefaultTableModel) tblSuppliers.getModel();
        model.setRowCount(0); // Clear table

        String query = "SELECT * FROM Supplier WHERE name LIKE ? OR contact_info LIKE ?";
        try (PreparedStatement pst = conn.prepareStatement(query)) {
            String searchPattern = "%" + keyword + "%";
            pst.setString(1, searchPattern);
            pst.setString(2, searchPattern);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("supplier_id"),
                    rs.getString("name"),
                    rs.getString("contact_info")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching Supplier: " + e.getMessage());
        }
    }

    public void updateSupplier(int id, String name, String contact) {
        String query = "UPDATE Supplier SET name=?, contact_info=? WHERE supplier_id=?";
        try (Connection conn = Dbconnect.getConnection(); PreparedStatement pst = conn.prepareStatement(query)) {
            pst.setString(1, name);
            pst.setString(2, contact);
            pst.setInt(3, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier updated successfully!");
            loadSupplier("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating Supplier: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UpdateSupplierbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductSupplier = new javax.swing.JTable();
        cmbProduct = new javax.swing.JComboBox<>();
        txtSupplier_name = new javax.swing.JTextField();
        btnClear1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        txtSupplierContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddSupplier1 = new javax.swing.JButton();
        UpdateSupplierbtn1 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1050, 570));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        setPreferredSize(new java.awt.Dimension(1050, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Suppliers:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 123, 36));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Association", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Serif", 1, 18))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 463));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 463));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 463));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Supplier");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Product:");
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        UpdateSupplierbtn.setBackground(new java.awt.Color(0, 153, 51));
        UpdateSupplierbtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        UpdateSupplierbtn.setText("Link Product to Supplier");
        UpdateSupplierbtn.setMaximumSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn.setMinimumSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn.setPreferredSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupplierbtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateSupplierbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 190, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suppliers products", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblProductSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Supplier ID", "Product ID", "Product Name", "Supplier ID", "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductSupplier);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1010, 150));

        cmbProduct.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(cmbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 200, 30));

        txtSupplier_name.setEditable(false);
        txtSupplier_name.setMaximumSize(new java.awt.Dimension(200, 30));
        txtSupplier_name.setMinimumSize(new java.awt.Dimension(200, 30));
        txtSupplier_name.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(txtSupplier_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 30));

        btnClear1.setBackground(new java.awt.Color(255, 255, 204));
        btnClear1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnClear1.setText("Clear");
        btnClear1.setMaximumSize(new java.awt.Dimension(70, 30));
        btnClear1.setMinimumSize(new java.awt.Dimension(70, 30));
        btnClear1.setPreferredSize(new java.awt.Dimension(70, 30));
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 30));

        jTextField6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextField6.setMinimumSize(new java.awt.Dimension(250, 30));
        jTextField6.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 190, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Search:");
        jLabel8.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 54, -1));

        jButton6.setText("Refresh");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 13, -1, -1));

        jButton7.setBackground(new java.awt.Color(204, 153, 0));
        jButton7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton7.setText("Detete Selected");
        jButton7.setMaximumSize(new java.awt.Dimension(88, 30));
        jButton7.setMinimumSize(new java.awt.Dimension(88, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(88, 30));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 130, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1030, 300));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(701, 392));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(701, 392));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(701, 392));

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 45, -1, 200));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Search:");
        jLabel7.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 30));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 54, -1));

        jTextField5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextField5.setMinimumSize(new java.awt.Dimension(250, 30));
        jTextField5.setPreferredSize(new java.awt.Dimension(250, 30));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jButton4.setText("Refresh");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 13, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 153, 0));
        jButton5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton5.setText("Detete Selected");
        jButton5.setMaximumSize(new java.awt.Dimension(88, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(88, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(88, 30));
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 130, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add a New Suppliers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Serif", 1, 18))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(320, 463));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 463));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 463));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Name:");
        jLabel4.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        txtSupplierName.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtSupplierName.setMaximumSize(new java.awt.Dimension(180, 30));
        txtSupplierName.setMinimumSize(new java.awt.Dimension(180, 30));
        txtSupplierName.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel2.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, -1, -1));

        txtSupplierContact.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtSupplierContact.setMaximumSize(new java.awt.Dimension(180, 30));
        txtSupplierContact.setMinimumSize(new java.awt.Dimension(180, 30));
        txtSupplierContact.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel2.add(txtSupplierContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("ContactNo:");
        jLabel5.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        btnAddSupplier1.setBackground(new java.awt.Color(0, 204, 204));
        btnAddSupplier1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnAddSupplier1.setText("Add");
        btnAddSupplier1.setMaximumSize(new java.awt.Dimension(70, 30));
        btnAddSupplier1.setMinimumSize(new java.awt.Dimension(70, 30));
        btnAddSupplier1.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAddSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplier1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddSupplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        UpdateSupplierbtn1.setBackground(new java.awt.Color(0, 153, 51));
        UpdateSupplierbtn1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        UpdateSupplierbtn1.setText("Update");
        UpdateSupplierbtn1.setMaximumSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn1.setMinimumSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn1.setPreferredSize(new java.awt.Dimension(70, 30));
        UpdateSupplierbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupplierbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateSupplierbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        btnClear2.setBackground(new java.awt.Color(255, 255, 204));
        btnClear2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnClear2.setText("Clear");
        btnClear2.setMaximumSize(new java.awt.Dimension(70, 30));
        btnClear2.setMinimumSize(new java.awt.Dimension(70, 30));
        btnClear2.setPreferredSize(new java.awt.Dimension(70, 30));
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 320, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateSupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupplierbtnActionPerformed
        int selectedRow = tblSuppliers.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) tblSuppliers.getValueAt(selectedRow, 0);
            String name = txtSupplierName.getText();
            String contact = txtSupplierContact.getText();

            if (name.isEmpty() || contact.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in both name and contactNo.");
                return;
            }

            updateSupplier(id, name, contact);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a branch to update.");
        }
    }//GEN-LAST:event_UpdateSupplierbtnActionPerformed

    private void btnAddSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplier1ActionPerformed
        String Name = txtSupplierName.getText();
        String contact = txtSupplierContact.getText();

        addSupplier(Name, contact);
    }//GEN-LAST:event_btnAddSupplier1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void UpdateSupplierbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupplierbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateSupplierbtn1ActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateSupplierbtn;
    private javax.swing.JButton UpdateSupplierbtn1;
    private javax.swing.JButton btnAddSupplier1;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JComboBox<ComboItem> cmbProduct;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblProductSupplier;
    private javax.swing.JTable tblSuppliers;
    private javax.swing.JTextField txtSupplierContact;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplier_name;
    // End of variables declaration//GEN-END:variables
}
